### ISSUE TITLE
Graphiql does not support offline access

### ISSUE THREAD

**Issue by PhenJuly** [Netflix/dgs-framework#108]
Will graphiql support offline access in the future？I'm looking forward to your support

**Comment by paulbakker** [comment]
What do you mean by that?

**Comment by PhenJuly** [comment]
when I start the project and access "http://localhost/graphiql" ,the js file of the page is loaded from “unpkg.com” 
eg: https://unpkg.com/graphiql/graphiql.min.js

If I'm not connected to the Internet, accessing  "http://localhost/graphiql"  fails, My expectation is that I can use graphiql to send requests normally

**Comment by paulbakker** [comment]
Ok, I get it now. That's a good point that I hadn't considered. 

So far we've preferred this mechanism because it always gets you the latest version, and you won't have to wait for a DGS release to get a GraphiQL update, but I can see how the online requirement can be problematic. It's a tradeoff, I'm not quite sure how to prioritize the options - hoping some others will chime in with ideas.

**Comment by paulbakker** [comment]
Closing issues that are stale and/or are no longer relevant after the DGS/Spring Graphql integration.
