### ISSUE TITLE
bug: DataFetchers not generated when using Kotlin

### ISSUE THREAD

**Issue by JamesPeters98** [Netflix/dgs-framework#1082]
## Expected behavior
DataFetcher would be generated as a kotlin class under the generated-examples folder

## Actual behavior
DataFetcher's only get generated when using the JAVA language type.

## Steps to reproduce
Run generateJava with these options:

```
tasks.withType<com.netflix.graphql.dgs.codegen.gradle.GenerateJavaTask> {
    language = "KOTLIN"
    generateClient = true
}
```

This took my a while to figure out why it wasn't working, and it isn't mentioned in the documentation anywhere when using Kotlin, so I figure this is probably just an oversight. Even if it still just generated them as Java classes that would be fine, as they're not intended to actually be used.

**Comment by springmonster** [comment]
Hi @JamesPeters98 , have you tried this configuration？
```
generateKotlinClosureProjections = true
```
I didn't actually try it, but it seems like could generate kotlin code.

Thanks very much!

**Comment by srinivasankavitha** [comment]
We don't support generating data fetchers in Kotlin (need to document this better). In fact, we will be dropping support for generating java data fetchers as well in the future since we don't actually maintain it actively.

`generateKotlinClosureProjections` is a different experimental feature and will not provide the functionality you are looking for.
