### ISSUE TITLE
Support for changing the GraphQL schema location

### ISSUE THREAD

**Issue by marceloverdijk** [Netflix/dgs-framework#141]
This is a follow up for https://github.com/Netflix/dgs-framework/issues/88 (closed).
DGS now already supports setting some options based on properties which is great.

It would be nice to be able to set the location of the `*.graphqls` schema files as well, like:

```
dgs.graphql.schema-location = classpath*:schema/**/*.graphql*
```

Rationale is that it currently looks in `schema` folder which by name is very generic.
I have some other (non GraphQL) schema related resources, so it would be nice to use a different folder.

**Comment by marceloverdijk** [comment]
After #128 is done I can provide a PR for this as well if you prefer. Will be an easy one.

**Comment by paulbakker** [comment]
Yes, that would be great! This is actually something that has come up many times already, so it's clearly something folks want/need.

**Comment by marceloverdijk** [comment]
OK, I looked into it a bit but it might be not that easy/straightforward...

What needs to be done is to be able pass a `baseDir`  to the `DgsSchemaProvider`  so that can be used in the `findSchemaFiles`.
`DgsSchemaProvider` is part of the `graphql-dgs` submodule so that class should not depend on any autoconfiguration stuff nor configuration properties classes. So we should just pass a `baseDir: String` to `DgsSchemaProvider` as mentioned.

The `DgsSchemaProvider` is instantiated from the `graphql-dgs-spring-boot-oss-autoconfigure`  submodule, but this module has no access to the recently added `DgsWebMvcConfigurationProperties`. Nor would it be smart to add it here as it is `WebMvc`  related.

The separation of `graphql-dgs-spring-boot-webmvc-autoconfigure` and `graphql-dgs-spring-boot-oss-autoconfigure` does not make it easier, but I guess this is done as the latter one is swapped out at Netflix and replaced with a Netflix specific one.

2 options to implement this:

1.  Introduce a `DgsConfigurationProperties` class in `graphql-dgs-spring-boot-oss-autoconfigure` similar as `DgsWebMvcConfigurationProperties`.
2. Use a `@Value("${dgs.graphql.schema-base-dir:schema}")` var in `DgsAutoConfiguration` to pass to the `DgsSchemaProvider` instead.

@bono007 @paulbakker which option do you prefer?

**Comment by bono007** [comment]
@marceloverdijk I was thinking about this ticket and was going to add some context this morning - but you beat me to it. And you found the thing I was going to write about. :) 

I am very much in favor of option 1 because it keeps our defaults in config props rather than in SpEL (one of the original motivations for the config props) and also because we are likely to have more properties added over time. 

If you are like me, you may ask yourself "Why am I creating this config props class when all I have is this one property?" Over time I have learned that it is ok to create the config props even if there is only 1 stinking lonely property in there. Because what happens (usually quickly) is that more properties find their way in there as features come.

**Comment by marceloverdijk** [comment]
Yes, I fully agree with your reasoning (I always created config properties classes for these things, even if there is only 1 property).
For this one it is a bit special as there are 2 autoconfigure modules.

I will go for option 1 and provide a PR later.

**Comment by paulbakker** [comment]
+1 for option one! Thanks for the careful explanation @marceloverdijk.
