### ISSUE TITLE
feature: Update to graphql-java:20.1

### ISSUE THREAD

**Issue by AlexanderPraegla** [Netflix/dgs-framework#1467]
## Describe the Feature Request
Do you plan to update to graphql-java:20.1 in the near future? The current version 6.0.1 is unfortunately not compatible:

```
Caused by: java.lang.NoSuchMethodError: 'graphql.ExecutionResultImpl graphql.ExecutionResultImpl$Builder.build()'
	at com.netflix.graphql.dgs.DgsExecutionResult$Builder.<clinit>(DgsExecutionResult.kt:143)
```

**Comment by spellew** [comment]
Thanks for creating this issue. We'll start looking into updating graphql-java

**Comment by setchy** [comment]
Now 20.2 - https://github.com/graphql-java/graphql-java/releases/tag/v20.2

**Comment by setchy** [comment]
In addition to updating the core graphql-java to 20.2, there are these related packages that should also be bumped to their 20.x equivalents
* graphql-java-extended-scalars: 19.0 -> [20.0](https://github.com/graphql-java/graphql-java-extended-scalars)
* graphql-java-extended-validation: 19.1 -> [20.0](https://github.com/graphql-java/graphql-java-extended-validation/releases/tag/20.0)
* federation-graphql-java-support: 2.1.0 -> [3.0.0](https://github.com/apollographql/federation-jvm/releases/tag/v3.0.0)

**Comment by srinivasankavitha** [comment]
Thanks @setchy. We are in the process of trying the upgrade to understand the scope of breaking changes. This may take a bit longer since we would like to keep our internal framework versions inline with the OSS versions as well and it's purely for convenience to avoid maintenance overhead. This will involve a major version update, as well, so we need to evaluate the scope a bit more before releasing this. Will post an update shortly with a more concrete timeframe.

**Comment by AlexanderPraegla** [comment]
Thank you for updating to graphql java 20.x.
