### ISSUE TITLE
feature: subscription HTTP callback support

### ISSUE THREAD

**Issue by dariuszkuc** [Netflix/dgs-framework#1771]
## Describe the Feature Request
GraphQL subscriptions enable clients to receive continual, real-time updates whenever new data becomes available. Unlike queries and mutations, subscriptions are long-lasting. This means a client can receive multiple updates from a single subscription.

WebSocket is the most commonly used subscription mechanism but it comes with few drawbacks - most notably it requires long lasting open connections. Apollo Router supports subscriptions using both the WebSocket and [HTTP callback](https://www.apollographql.com/docs/router/executing-operations/subscription-callback-protocol/) mechanism. HTTP callback protocol allows GraphQL servers to asynchronously send their subscription updates using regular HTTP POST requests which in turn allows you to scale you servers more easily.

[HTTP callback protocol flow](https://www.apollographql.com/docs/router/executing-operations/subscription-callback-protocol/)
* initialization
  * router generates new unique subscription ID
  * routers sends subscription operation with additional extension data using regular HTTP POST request
  * subgraph responds with a `check` message
  * router responds with HTTP 204 (if successful)
  * subgraph responds with empty `{ "data": null }` GraphQL response
* main loop (run on some background thread)
  * subgraph sends heartbeats every X milliseconds (if enabled)
  * whenever new data is available, subgraph sends `next` message followed by `complete` message at the end of the stream

See also:
* `federation-jvm` `spring-graphl` implementation of the protocol [[link](https://github.com/apollographql/federation-jvm/pull/354) [fix](https://github.com/apollographql/federation-jvm/pull/360)]

## Describe Preferred Solution
DGS provides out of the box support for subscriptions using HTTP callback protocol.

## Describe Alternatives
WebSocket based subscriptions are still viable option but don't scale as nicely.

**Comment by srinivasankavitha** [comment]
It looks like the PR you created in federation-jvm adds implements support
for Http callback protocol for spring-graphql projects. We are currently
working on integrating with spring-graphql in the DGS framework. I expect
this feature would be available for free when that is released later this
quarter. Rather than reimplementing this same logic in the framework, it
would be preferable to leverage what is in the federation-jvm library
already.

**Comment by dariuszkuc** [comment]
👍 Sounds good! Feel free to close the issue (or to keep it around until `spring-graphql` integration is completed).

**Comment by gwardwell** [comment]
It looks like DGS [v8.3.0](https://github.com/Netflix/dgs-framework/releases/tag/v8.3.0) updates to [federation-jvm v4.4.0](https://github.com/apollographql/federation-jvm/releases/tag/v4.4.0). Support for subscription callbacks was added in [federation-jvm 4.2.0](https://github.com/apollographql/federation-jvm/releases/tag/v4.2.0). Does this mean that DGS should support subscriptions via HTTP callback now? Or is it still blocked by the mentioned spring-graphql support since I see that work is being done in v8.2.6 RC releases?

**Comment by srinivasankavitha** [comment]
Support for HTTP callbacks will be available in the spring-graphql integration in a future release, It is not available yet on existing releases.

**Comment by gwardwell** [comment]
Does the [release of DGS 8.5.0](https://github.com/Netflix/dgs-framework/releases/tag/v8.5.0) with Spring GraphQL integration mean subscription HTTP callbacks are now supported?

**Comment by paulbakker** [comment]
Yes, with
https://github.com/apollographql/federation-jvm?tab=readme-ov-file#subscription-http-callback-support-for-spring-graphql

**Comment by dariuszkuc** [comment]
As stated above it should be already supported.
