### ISSUE TITLE
RelayConnectionFactory

### ISSUE THREAD

**Issue by sisekipp** [Netflix/dgs-framework#25]
Is it possible to use the RelayConnectionFactory from the GraphQL Java Tools?

**Comment by paulbakker** [comment]
From a purely technical perspective, you probably could by plugging it in using this: https://netflix.github.io/dgs/advanced/schema-from-code/, which basically allows you to register a TypeDefinitionFactory.

At Netflix we prefer having the Connection etc. explicitly in the schema though, because it make the schema more clear and because Connections need additional properties in many cases. We have discussed more automated ways for doing so, but in the end learned the clarity is worth the (little) extra effort in the schema.

If you decide to give the RelayConnectionFactory a try, please do report back with your findings, it would be interesting to learn more about it.

**Comment by sisekipp** [comment]
If I see it correctly, I can't integrate the factory directly but have to rebuild what it does with ObjectTypeExtensionDefinition.

**Comment by paulbakker** [comment]
If you create your own `TypeDefinitionRegistry` like described in the docs, can't you from there call the factory and have those types created, which you then add to the registry?
Again, I haven't actually tried this, so I might be wrong.

**Comment by paulbakker** [comment]
Closing this as it was a question. Please reopen with more information if more is needed.
