### ISSUE TITLE
feature: prometheus histogram metrics

### ISSUE THREAD

**Issue by sbilello** [Netflix/dgs-framework#321]
## Describe the Feature Request
Add Histogram metrics support https://prometheus.io/docs/practices/histograms/
## Describe Preferred Solution
Annotation-based approach.

**Comment by berngp** [comment]
Hi @sbilello, we are using [Micrometer](https://micrometer.io/) as the mechanism to capture the metrics and they meters can be configured to [export percentiles](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#per-meter-properties). Its a matter of just setting `management.metrics.distribution.percentiles-histogram.gql=true`.

**Comment by berngp** [comment]
@sbilello I think unless there is a specific feature that you suggest for the DGS framework, this looks more like a Q&A discussion.

**Comment by sbilello** [comment]
This is cool! Thanks, @berngp! 
Yes, we can move this as Q&A but I was wondering if it would make sense to specify the percentiles as part of the configuration to reduce the number of buckets. See something like https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/annotation/Timed.java#L54

 I was also wondering why we have different labels for the metrics:

```
gql_query_seconds_bucket{gql_queryComplexity="25",outcome="success",le="0.001",} 0.0
gql_resolver_seconds_bucket{gql_field="Query.getUserByUserIdInput",outcome="success",le="7.158278826",} 20.0
```

I will work on a custom tag as described in the [doc](https://netflix.github.io/dgs/advanced/instrumentation/#further-tag-customization) unless we can not make consistent the tags between these 2 metrics.
 
I would like to show the duration in percentiles by `query name` for the `gql_resolver*` and the `gql_query*` metrics

**Comment by berngp** [comment]
Not sure I understand which labels are you referring to on `gql.query` vs `gql.resolver`.
The `gql.query` captures the entire scope of the GraphQL Query. Since each GraphQL Query can have multiple fields we can't capture them as part of the `gql.query` tag, I don't believe there is a way to express an array of values associated to a tag puls the cardinality will be problematic. The `gql.resolver` on the other hand can capture the _GraphQL Field_ and therefore is able to include it.
