### ISSUE TITLE
Improve WebFlux sample

### ISSUE THREAD

**Issue by itsandreramon** [Netflix/dgs-framework#331]
The current sample does not reflect how a real application would be build.

**Comment by paulbakker** [comment]
Maybe provide a little more detail of "how a real application would be built"?

**Comment by paulbakker** [comment]
The actual code (data fetchers and such) is (mostly) in the `graphql-dgs-example-shared` module, which is shared between the WebMVC and WebFlux examples.

They way you write the DGS code is exactly the same between the two. Datafetchers don't have to return Mono, this is internally taken care of. Although adding support for directly Mono would probably be a good addition.

I do want to set up a separate WebFlux example project as well, just to show the actual dependencies instead of the project dependencies for the internal example.

**Comment by itsandreramon** [comment]
Yes I've seen the shared module, but still not really straight forward for someone new imo.

**Comment by paulbakker** [comment]
Created a new example app as well now: https://github.com/Netflix/dgs-examples-webflux
