### ISSUE TITLE
feature: Add a default Cors configuration 

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#414]
Currently, I have to add a custom configuration to enable Cors.

https://github.com/hantsy/spring-graphql-sample/blob/master/dgs-subscription-ws/src/main/kotlin/com/example/demo/DemoApplication.kt#L17

Hope there is a default configuration for `/graphql` endpoint. (and SSE endpoint if using sse)

**Comment by paulbakker** [comment]
Because CORS is very specific to each application, and there are some dangers in not knowing it's enabled, I think we should **not** support this out of the box. @berngp WDYT?

**Comment by hantsy** [comment]
Add a `CorsFilter` is on conditional, as it was done in the graphql-java-kickstart spring boot starter.

**Comment by paulbakker** [comment]
What should be the default configuration? E.g. what hostnames should be allowed?

**Comment by hantsy** [comment]
@paulbakker  add all hosts to allow by default.

**Comment by paulbakker** [comment]
Discussed this some more with @berngp and @srinivasankavitha offline, and we think it's best *not* to do this. It can be unexpected and possibly dangerous. Also, there isn't really a great set of defaults that works for everyone.

Since it's well documented and easy to "fix" the issue in Spring, it's probably best to not try to solve this.
