### ISSUE TITLE
Upgrade Java to latest accepted version

### ISSUE THREAD

**Issue by yrashish** [Netflix/dgs-framework#48]
I am not sure if community contributions are accepted. But are there any specific reasons for using Java 8?. It's quite old and most frameworks have already started supporting the latest stable release version of Java.

**Comment by srinivasankavitha** [comment]
Yes, we do welcome community contributions. We use Java 8 internally within the company and hence the framework does so. As a consumer of the framework, however, you are not restricted to that.

**Comment by paulbakker** [comment]
There is actually still a lot of Java 8 usage out there. This is unfortunate, but a reality. 
Since the framework is mostly written in Kotlin, the Java version doesn’t actually matter all that much for the framework development. One benefit of this is that we can easily still support Java 8 without slowing down framework development.

And you can off course _use_ the framework with any newer Java version.
