### ISSUE TITLE
Datafetchers as completable futures don't run in parallel

### ISSUE THREAD

**Issue by prograhammer** [Netflix/dgs-framework#512]
### Discussed in https://github.com/Netflix/dgs-framework/discussions/509

<div type='discussions-op-text'>

<sup>Originally posted by **prograhammer** August  2, 2021</sup>
I created two simple datafetchers as completable futures but they don't run in parallel. What am I missing here?

Simple schema:
![image](https://user-images.githubusercontent.com/4474660/127939638-1896f998-eaa0-4cc6-a4de-51e583594931.png)

Users DataFetcher:

![image](https://user-images.githubusercontent.com/4474660/127939698-3c53cdf8-ead1-41a9-ba99-308c9887f93e.png)

Products DataFetcher:
![image](https://user-images.githubusercontent.com/4474660/127939731-8c509bbc-86f0-42ef-a214-1c1862bc4fa6.png)

They don't run in parallel:
![image](https://user-images.githubusercontent.com/4474660/127939755-dcd7e14f-3d76-486e-ad54-f77eaf4c51f9.png)

I could create the futures and join them within a single datafetcher but that defeats the nice annotation ability of DGS right? It is because one is Query and the other is an Object Type (on different levels, so-to-speak)?</div>

I've also tried passing in an executor as @paulbakker suggested (although I may need an example of how this is done to ensure I'm not wrong):

```java
  @Autowired
  private ExecutorService executorService;

  @DgsData(parentType = "Query", field = "users")
  public CompletableFuture<List<User>> getUsers(DataFetchingEnvironment dfe) {

    String userId = dfe.getArgument("userId");

    return CompletableFuture.supplyAsync(() -> {
      try {
          System.out.println("User task execution started.");
          Thread.sleep(5000);
          System.out.println("User task execution stopped.");
      } catch (Exception e) {
          e.printStackTrace();
      }
      return users;
    }, executorService.getExecutor());
```

**Comment by paulbakker** [comment]
It took me a minute to figure out what's going on. The problem comes from the relation between `User` and `Product`. Because `products` is a field of `User`, it first needs to resolve the parent (`User` in this case) before it can continue to resolve subfields.
Imagine for example that your `products` datafetcher would use the `getSource` method to get its parent (the `User`). That wouldn't work if `User` wasn't resolved yet.

If products and user were two unrelated fields on `Query`, your code would work. I also found that my suggestion about using an `Executor` isn't actually required.

We have a simple test in the example embedded in the framework's repository that demonstrates this: https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs-example-shared/src/test/java/com/netflix/graphql/dgs/example/shared/ConcurrentDataFetcherTest.java

Of course, that doesn't answer the question how you _could_ make such a scenario parallel. I think the best option is a "look ahead" data fetcher as described here: https://netflix.github.io/dgs/advanced/context-passing/#pre-loading.

I'm closing this issue because I don't think it's further actionable, but feel free to ask more questions.

**Comment by prograhammer** [comment]
Hi @paulbakker , yeah that's what I was thinking. Thank you so much for confirming my suspicion. Makes sense.

I actually ended up doing this to try to get something parallel going:

![image](https://user-images.githubusercontent.com/4474660/128445934-5a853a8e-c10a-41a7-a4b5-bde4b67ded5c.png)

(I'm just playing with DGS to see what it can do). But now I'll look at some of those other suggestions you linked to (assuming I find myself in this situation in my real application I plan to work on later). 

Thanks!
