### ISSUE TITLE
Apollo Federation 2 support

### ISSUE THREAD

**Issue by hwillson** [Netflix/dgs-framework#997]
Hi all! We (Apollo) are getting ready to publish a new major version of https://github.com/apollographql/federation-jvm that includes Federation 2 support. We just finished testing the latest Federation JVM alpha (`com.apollographql.federation:federation-graphql-java-support:2.0.0-alpha.5`) with DGS and the great news is that everything appears to be working well:

![Image 2022-04-20 at 4 57 48 PM](https://user-images.githubusercontent.com/137740/164324124-9e24f8fd-2215-4100-8847-b8dceca8915c.jpg)

After we've published Federation JVM 2.0, would you be interested in a PR to update DGS accordingly? Thanks!

**Comment by srinivasankavitha** [comment]
@hwillson - that's awesome and thank you for testing it with the DGS! We do have a few users who have asked about this already, so this is great timing. If you are able to contribute a PR that would be super helpful. The question I have is whether this is fully backwards compatible with existing federation. Our internal services and gateway will still be on Federation 1.x and will not be ready to switch till later this year. If not, we'll need to make it a conditional so that users are able to opt-in.

@berngp - any thoughts?

**Comment by berngp** [comment]
@hwillson thanks for doing all these work. I agree with @srinivasankavitha's point.
> The question I have is whether this is fully backwards compatible with existing federation.

**Comment by srinivasankavitha** [comment]
Just looked at the docs and seems like 1) They don't require any changes to
stay on Federation 1.x and 2) We can explicitly opt in to Federation 2.0.
The only catch seems to be that some situations where the schema is not
fully federation compliant may fail because they were not correct to begin
with. We just need to watch out for those for internal usage.

**Comment by hwillson** [comment]
@srinivasankavitha @berngp correct, this is all fully backwards compatible. Fed 2 support is opt in - we'll get a PR together, thanks!

And regarding:

> The only catch seems to be that some situations where the schema is not fully federation compliant may fail because they were not correct to begin with.

we've developed a tool to check federated schema's for Fed 2 compatibility to help find any issues before migrating: https://github.com/apollosolutions/federation-2-readiness

**Comment by hwillson** [comment]
👋 all - @dariuszkuc is going to be helping with this shortly. Thanks!

**Comment by berngp** [comment]
Hi @dariuszkuc, thanks for helping out. We recently merged  PR #1056  with the upgrade to [federation 2.0](https://github.com/Netflix/dgs-framework/pull/1056/files#diff-d78ac8d3d0eb2a2244a902c3c0ee332c2d58b6ca2e1fe8d23e00c7a35e21623f), is there anything else we should be doing?

**Comment by dariuszkuc** [comment]
Hello 👋 
Yeah I just started looking into this and it seems like #1056 resolves this issue. I believe this can be closed.

**Comment by berngp** [comment]
Thanks @dariuszkuc !

**Comment by srinivasankavitha** [comment]
Is there anything we need to do on our side from a validation perspective?

**Comment by dariuszkuc** [comment]
@srinivasankavitha I've opened a draft PR https://github.com/apollographql/apollo-federation-subgraph-compatibility/pull/96 that validates framework compatibility with Apollo Federation. I'll update the PR once new version of DGS is released.
